tableName: testing-table123
AWS_REGION: us-east-1
BUCKET_NAME: test-sdk-golang-dummy
KMS_KEY: sdk
IMAGE_ID: ami-02f3f602d23f1659d
INSTANCE_TYPE: t2.micro
GROUP_NAME: sdk
ALARM_NAME: sdk
SECURITYGROUP_NAME: my-securitygroup-sdk
VPC_ID: vpc-034c17f99ea7c941d
TARGETGROUP_NAME1: my-targetgroup1-sdk 
TARGETGROUP_NAME2: my-targetgroup2-sdk
TARGETGROUP_NAMES:
  - my-targetgroup1-sdk 
  - my-targetgroup2-sdk 
ALB_NAME: alb-sdk
Sgfrom_PORT1: 8000
Sgto_PORT1: 8000
Sgfrom_PORT2: 8080
Sgto_PORT2: 8080
TG1PORT: 8000
TG2PORT: 8080
LISTENER1PORT: 8000
LISTENER2PORT: 8080
TARGETGROUP_ARN1: arn:aws:elasticloadbalancing:us-east-1:554248189203:targetgroup/my-targetgroup1-sdk/72ae1e3bd98290aa
TARGETGROUP_ARN2: arn:aws:elasticloadbalancing:us-east-1:554248189203:targetgroup/my-targetgroup2-sdk/761d4cb21979f98c
INSTANCE_ID: i-00a0a13d69b4bbc15